#!/bin/sh
grep 'DMPI' ../config_amber.h > checkpar
if [ -s checkpar ]; then
	/bin/rm -f checkpar
	echo "Error: ../config_amber.h is not set up for serial compilation"
	exit 1
else
	/bin/rm -f checkpar
	exit 0
fi
